title: Real Iterations
description: The technical blog of front end developer Réal Provencher

url: http://therealest.github.io
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
redcarpet:
  extensions: [with_toc_data,no_intra_emphasis,tables,autolink]
highlighter: pygments
paginate: 5

navigation:
  - title: Home
    url: /
  # - title: Code
  #   url: /code
  # - title: Contact
  #   url: /contact

social:
  github: therealest
  twitter: RRProvencher
  facebook: ryanprov
  email: real@rrprovencher.com

collections:
  code:
    output: true
    permalink: /code/:path/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
  -
    scope:
      path: ""
      type: code
    values:
      layout: code

disqus_shortname: "therealestio"
google_analytics: "UA-62858600-1"
