title: Real Iterations
description: The technical blog of front end developer Réal Provencher

url: http://therealest.github.io
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: therealest
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: real@rrprovencher.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# google_analytics: "UA-58263416-1"
